import type { Metadata } from "next";
import "./globals.css";
import Providers from "./providers"
import React from "react";
import {Plus_Jakarta_Sans, IBM_Plex_Mono, Lora } from "next/font/google"

const plusJakartaSans = Plus_Jakarta_Sans({
    subsets: ["latin"],
    variable: "--font-plus-jakarta-sans",
})

const IBMPlexMono = IBM_Plex_Mono({
    weight: "400",
    subsets: ["latin"],
    variable: "--font-ibm-plex-mono"
})

const lora = Lora({
    weight: "400",
    subsets: ["latin"],
    variable: "--font-lora"
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning className={`${plusJakartaSans.variable} ${lora.variable} ${IBMPlexMono.variable}`}>
      <body
      >
      <Providers>
        {children}
      </Providers>
      </body>
    </html>
  );
}
