import type { Metadata } from "next";
import "./globals.css";
import Providers from "./providers"
import React from "react";
import {Geist, Fira_Code, Lora } from "next/font/google"

const geist = Geist({
    subsets: ["latin"],
    variable: "--font-geist"
})

const fira_code = Fira_Code({
    weight: "400",
    subsets: ["latin"],
    variable: "--font-fira"
})

const lora = Lora({
    weight: "400",
    subsets: ["latin"],
    variable: "--font-lora"
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning className={`${geist.variable} ${lora.variable} ${fira_code.variable}`}>
      <body
      >
      <Providers>
        {children}
      </Providers>
      </body>
    </html>
  );
}
